---
apiVersion: v1
kind: Namespace
metadata:
  name: test


# test services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-web
  template:
    metadata:
      labels:
        app: test-web
    spec:
      containers:
        - name: nginx
          image: nginx
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: test-web
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: test-web
  ports:
    - name: main
      port: 80
      targetPort: 80
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web2
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-web2
  template:
    metadata:
      labels:
        app: test-web2
    spec:
      containers:
        - name: nginx
          image: nginx
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: test-web2
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: test-web2
  ports:
    - name: main
      port: 8080
      targetPort: 80
      protocol: TCP


# access
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consistelancer
  namespace: test
  labels:
    app: consistelancer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consistelancer-admin
subjects:
  - kind: ServiceAccount
    name: consistelancer
    namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # accessToServices


# database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: main
      port: 6379
      targetPort: 6379
      protocol: TCP
