---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consistelancer
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consistelancer
  template:
    metadata:
      labels:
        app: consistelancer
    spec:
      serviceAccountName: consistelancer
      containers:
        - name: app
          imagePullPolicy: Never # for dev only
          image: consistelancer # dev tag
          resources: {}
          # env:
          #   - name: LOG_LEVEL
          #     value: info

