# https://skaffold.dev/docs/references/yaml/
---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: consistelancer
build:
  artifacts:
  - image: consistelancer
    ko:
      fromImage: alpine #golang:1.17-alpine
      dir: src
      dependencies:
        paths:
        - "src/*"
        - "k8s/*"
        - "skaffold.yaml"
        ignore: []
          # - README.md
          # - LICENSE
          # - example
deploy:
  kubectl:
    manifests:
      - k8s/app.yaml
portForward:
  - resourceType: Service
    resourceName: consistelancer
    namespace: test
    port: 8080
    address: 127.0.0.1
    localPort: 8080
