apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: consistelancer
build:
  artifacts:
  - image: consistelancer
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s.yaml
